# Generated by Django 4.0.3 on 2022-04-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ANA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tts_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vms_user',
        ),
    ]
