# Generated by Django 4.0.2 on 2022-02-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANA', '0002_rename_forgotpassword_ana_forgotpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ana_user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
