# Generated by Django 4.0.2 on 2022-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANA', '0003_ana_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ana_user',
            name='tfa_secret',
            field=models.CharField(default='', max_length=255),
        ),
    ]
